# Generated by Django 4.1 on 2022-11-28 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(max_length=20)),
                ('duration', models.TextField(max_length=10)),
                ('fees', models.CharField(max_length=20)),
            ],
        ),
    ]
