# Generated by Django 4.1 on 2022-11-28 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0003_fees'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Fees',
        ),
    ]
