# Generated by Django 4.1 on 2022-11-28 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0004_delete_fees'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fees', models.CharField(max_length=15)),
                ('date', models.TextField(max_length=20)),
            ],
        ),
    ]
